name: 构建镜像并推送到Docker Hub
on: push

permissions:
  contents: write
jobs:
  npm-build:
    name: npm_build_workflow
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 登录docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 构建镜像并且推送到Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest
