on: push

jobs:
  npm-build:
    name: npm_build_workflow
    runs-on: ubuntu-latest
    steps:
    - name: read repo
      uses: actions/checkout@v4
    - name: 安装依赖
      run: npm install
    - name: 构建项目
      run: npm run build
